name: Flutter Build and Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Rename APK with version
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/nic-app-${{ github.ref_name }}.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/nic-app-${{ github.ref_name }}.apk
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y ruby ruby-dev
          gem install github_changelog_generator --user-install
          echo "Adding gem executables to PATH"
          export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: release-assets/
      - name: Generate Release Notes with GitHub Changelog Generator
        run: |
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project $(basename ${{ github.repository }}) \
            --token ${{ secrets.PAT_FOR_NIC_DEC }} \
            --output release-notes.md \
            --header-label "ğŸš€ **Latest Release: ${{ github.ref_name }}**" \
            --breaking-label "**ğŸ’¥ Breaking Changes:**" \
            --enhancement-label "**âœ¨ Enhancements:**" \
            --bug-label "**ğŸ› Bug Fixes:**" \
            --issues-label "**ğŸ“‹ Other Changes:**" \
            --exclude-labels "skip-changelog,duplicate,invalid,wontfix" \
            --pull-requests \
            --verbose
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          prerelease: true
          artifacts: release-assets/
          name: ${{ github.ref_name }}
          bodyFile: release-notes.md
          token: ${{ secrets.PAT_FOR_NIC_DEC }}
